# GPT NER evaluation configuration - FIXED VERSION

strategies: [zero_shot, few_shot]

# IMPORTANT: Use proper sample size (not commented out!)
sample_size: 200  # Use 200 samples for meaningful evaluation

# Use batch processing for efficiency
force_batch: true
batch_threshold: 100

wandb:
  project: gpt-ner-evaluation
  entity: null
  mode: online     # (online, offline, disabled)

azure:
  deployment: gpt-4o-mini